#!/bin/sh
set -e

case "$1" in
remove|deconfigure)
	if command -v systemctl >/dev/null 2>&1; then
		systemctl stop backupurvm-client.service >/dev/null 2>&1 || true
		systemctl disable backupurvm-client.service >/dev/null 2>&1 || true
	fi
	;;
upgrade)
	if command -v systemctl >/dev/null 2>&1; then
		systemctl stop backupurvm-client.service >/dev/null 2>&1 || true
	fi
	;;
esac

exit 0
